-- =====================================================================
-- Portal rw2.5t4d10.com — Migración 008
-- Motor de sincronización de permisos Bettermode (cron 12h, idempotente).
--   - program_config        : config de vigencia por programa (sin lógica quemada)
--   - user_program_validity : vigencias calculadas por usuario (auditoría)
--   - permission_sync_runs  : corridas del sync (resync_runs ya está tomado por otro proceso)
--   - reconcilia bettermode_spaces a las listas EXACTAS del brief (space_id = verdad)
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1) Config de vigencia por programa (product_key reusa la nomenclatura existente)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.program_config (
    product_key                  TEXT PRIMARY KEY,
    access_type                  TEXT NOT NULL CHECK (access_type IN ('subscription','fixed_days')),
    source_table                 TEXT NOT NULL CHECK (source_table IN ('subscriptions','sales')),
    requires_active_subscription BOOLEAN NOT NULL DEFAULT FALSE,
    valid_days                   INT,                 -- solo fixed_days
    requires_program_key         TEXT,                -- dependencia (infinity_vip -> infinity)
    valid_statuses               TEXT[] NOT NULL,     -- statuses que cuentan como vigente
    is_active                    BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order                   INT NOT NULL DEFAULT 0,
    created_at                   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
DROP TRIGGER IF EXISTS trg_program_config_updated_at ON public.program_config;
CREATE TRIGGER trg_program_config_updated_at BEFORE UPDATE ON public.program_config
    FOR EACH ROW EXECUTE FUNCTION public.tg_set_updated_at();

INSERT INTO public.program_config
    (product_key, access_type, source_table, requires_active_subscription, valid_days, requires_program_key, valid_statuses, sort_order) VALUES
    ('infinity',       'subscription', 'subscriptions', TRUE,  NULL, NULL,       ARRAY['ACTIVE','DELAYED','STARTED','OVERDUE'], 1),
    ('infinity_vip',   'subscription', 'subscriptions', TRUE,  NULL, 'infinity', ARRAY['ACTIVE','DELAYED','STARTED','OVERDUE'], 2),
    ('mommy_comeback', 'fixed_days',   'sales',         FALSE, 80,   NULL,       ARRAY['COMPLETE','APPROVED'],                 3),
    ('xtreme_burn',    'fixed_days',   'sales',         FALSE, 24,   NULL,       ARRAY['COMPLETE','APPROVED'],                 4)
ON CONFLICT (product_key) DO UPDATE SET
    access_type=EXCLUDED.access_type, source_table=EXCLUDED.source_table,
    requires_active_subscription=EXCLUDED.requires_active_subscription, valid_days=EXCLUDED.valid_days,
    requires_program_key=EXCLUDED.requires_program_key, valid_statuses=EXCLUDED.valid_statuses,
    is_active=TRUE, sort_order=EXCLUDED.sort_order;

-- ---------------------------------------------------------------------
-- 2) Vigencias calculadas por usuario (auditoría / soporte)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_program_validity (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id        BIGINT NOT NULL,
    email         TEXT NOT NULL,
    product_key   TEXT NOT NULL,
    is_valid      BOOLEAN NOT NULL,
    reason        TEXT,
    valid_until   TIMESTAMPTZ,
    source_status TEXT,
    computed_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_upv_run   ON public.user_program_validity (run_id);
CREATE INDEX IF NOT EXISTS idx_upv_email ON public.user_program_validity (LOWER(email));

-- ---------------------------------------------------------------------
-- 3) Corridas del sync de permisos
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.permission_sync_runs (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at      TIMESTAMPTZ,
    mode             TEXT NOT NULL DEFAULT 'apply' CHECK (mode IN ('apply','dry_run')),
    status           TEXT NOT NULL DEFAULT 'running'
                     CHECK (status IN ('running','success','partial','failed','aborted_locked')),
    users_processed  INT NOT NULL DEFAULT 0,
    users_changed    INT NOT NULL DEFAULT 0,
    grants_ok        INT NOT NULL DEFAULT 0,
    grants_failed    INT NOT NULL DEFAULT 0,
    revokes_ok       INT NOT NULL DEFAULT 0,
    revokes_failed   INT NOT NULL DEFAULT 0,
    accounts_created INT NOT NULL DEFAULT 0,
    accounts_missing INT NOT NULL DEFAULT 0,
    trigger_source   TEXT,
    message          TEXT
);
CREATE INDEX IF NOT EXISTS idx_psr_started ON public.permission_sync_runs (started_at DESC);

-- ---------------------------------------------------------------------
-- 4) Reconciliar bettermode_spaces a las listas EXACTAS del brief
--    (space_id es la referencia oficial; nombres solo descriptivos)
-- ---------------------------------------------------------------------
-- infinity (20): ya correcto en BD (incluye Soporte y 8EIGHT MAX.). Sin cambios.

-- infinity_vip: los 5 EXTRA = 3 actuales + XTREME BURN y XTREME BURN.
INSERT INTO public.bettermode_spaces (product_key, space_id, space_name, sort_order) VALUES
    ('infinity_vip', 'GD8b7iMXB8jv', 'XTREME BURN',  4),
    ('infinity_vip', 'VAo3TjguHoIt', 'XTREME BURN.', 5)
ON CONFLICT (product_key, space_id) DO UPDATE SET is_active=TRUE, space_name=EXCLUDED.space_name;

-- mommy_comeback (9): quitar Soporte (no está en la spec)
UPDATE public.bettermode_spaces SET is_active=FALSE
 WHERE product_key='mommy_comeback' AND space_id='RSsaEWDqbmuh';

-- xtreme_burn (9): quitar Soporte (no está en la spec)
UPDATE public.bettermode_spaces SET is_active=FALSE
 WHERE product_key='xtreme_burn' AND space_id='RSsaEWDqbmuh';
